networks:
  network:



services:

  backend:
    depends_on:
      - db
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    networks:
      - network
  
  nginx:
    depends_on:
      - backend
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    networks:
      - network

  db:
    image: postgres:17
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    networks:
      - network

    